

* Requirements
** Ctrl, Alt, Shift Modifiers
   Ctrl, Alt and Shift will act as modifiers to add addition keys for input.

** Other keystrokes can be considered modifiers
   If a certain keystroke is set as a modifier, it can be changed into other
   commands. EX. C-z a

* Notes
** Key Command Sequence
   * Store previous command if its a prefix
   * Modifier Key Pressed
     * On event loop, store value, either C-, M- or S-
   * Regular Key Pressed
     * On event loop, perform lookup and store string value
   * If key is not empty
     * Append modifer then key to command string
     * Perform hashmap lookup
     * If value is found
       * Execute associated command
       * Clear command string
** Repeated key commands
   * HandleKeyPress
     * Will start executing the given command immediately, and will check if it
       should be repeated.
* Development Notes

* Code Snippets
** Additional Cases for keyboard
#+BEGIN_SRC C++
  switch(key)
  {
  case sf::Keyboard::A:

     break;
  case sf::Keyboard::B:

     break;
  case sf::Keyboard::C:

     break;
  case sf::Keyboard::D:

     break;
  case sf::Keyboard::E:

     break;
  case sf::Keyboard::F:

     break;
  case sf::Keyboard::G:

     break;
  case sf::Keyboard::H:

     break;
  case sf::Keyboard::I:

     break;
  case sf::Keyboard::J:

     break;
  case sf::Keyboard::K:

     break;
  case sf::Keyboard::L:

     break;
  case sf::Keyboard::M:

     break;
  case sf::Keyboard::N:

     break;
  case sf::Keyboard::O:

     break;
  case sf::Keyboard::P:

     break;
  case sf::Keyboard::Q:

     break;
  case sf::Keyboard::R:

     break;
  case sf::Keyboard::S:

     break;
  case sf::Keyboard::T:

     break;
  case sf::Keyboard::U:

     break;
  case sf::Keyboard::V:

     break;
  case sf::Keyboard::W:

     break;
  case sf::Keyboard::X:

     break;
  case sf::Keyboard::Y:

     break;
  case sf::Keyboard::Z:

     break;
  case sf::Keyboard::Num0:

     break;
  case sf::Keyboard::Num1:

     break;
  case sf::Keyboard::Num2:

     break;
  case sf::Keyboard::Num3:

     break;
  case sf::Keyboard::Num4:

     break;
  case sf::Keyboard::Num5:

     break;
  case sf::Keyboard::Num6:

     break;
  case sf::Keyboard::Num7:

     break;
  case sf::Keyboard::Num8:

     break;
  case sf::Keyboard::Num9:

     break;
  case sf::Keyboard::Escape:

     break;
  case sf::Keyboard::LControl:

     break;
  case sf::Keyboard::LShift:

     break;
  case sf::Keyboard::LAlt:

     break;
  case sf::Keyboard::LSystem:

     break;
  case sf::Keyboard::RControl:

     break;
  case sf::Keyboard::RShift:

     break;
  case sf::Keyboard::RAlt:

     break;
  case sf::Keyboard::RSystem:

     break;
  case sf::Keyboard::Menu:

     break;
  case sf::Keyboard::LBracket:

     break;
  case sf::Keyboard::RBracket:

     break;
  case sf::Keyboard::SemiColon:

     break;
  case sf::Keyboard::Comma:

     break;
  case sf::Keyboard::Period:

     break;
  case sf::Keyboard::Quote:

     break;
  case sf::Keyboard::Slash:

     break;
  case sf::Keyboard::BackSlash:

     break;
  case sf::Keyboard::Tilde:

     break;
  case sf::Keyboard::Equal:

     break;
  case sf::Keyboard::Dash:

     break;
  case sf::Keyboard::Space:

     break;
  case sf::Keyboard::Return:

     break;
  case sf::Keyboard::BackSpace:

     break;
  case sf::Keyboard::Tab:

     break;
  case sf::Keyboard::PageUp:

     break;
  case sf::Keyboard::PageDown:

     break;
  case sf::Keyboard::End:

     break;
  case sf::Keyboard::Home:

     break;
  case sf::Keyboard::Insert:

     break;
  case sf::Keyboard::Delete:

     break;
  case sf::Keyboard::Add:

     break;
  case sf::Keyboard::Subtract:

     break;
  case sf::Keyboard::Multiply:

     break;
  case sf::Keyboard::Divide:

     break;
  case sf::Keyboard::Left:

     break;
  case sf::Keyboard::Right:

     break;
  case sf::Keyboard::Up:

     break;
  case sf::Keyboard::Down:

     break;
  case sf::Keyboard::Numpad0:

     break;
  case sf::Keyboard::Numpad1:

     break;
  case sf::Keyboard::Numpad2:

     break;
  case sf::Keyboard::Numpad3:

     break;
  case sf::Keyboard::Numpad4:

     break;
  case sf::Keyboard::Numpad5:

     break;
  case sf::Keyboard::Numpad6:

     break;
  case sf::Keyboard::Numpad7:

     break;
  case sf::Keyboard::Numpad8:

     break;
  case sf::Keyboard::Numpad9:

     break;
  case sf::Keyboard::F1:

     break;
  case sf::Keyboard::F2:

     break;
  case sf::Keyboard::F3:

     break;
  case sf::Keyboard::F4:

     break;
  case sf::Keyboard::F5:

     break;
  case sf::Keyboard::F6:

     break;
  case sf::Keyboard::F7:

     break;
  case sf::Keyboard::F8:

     break;
  case sf::Keyboard::F9:

     break;
  case sf::Keyboard::F10:

     break;
  case sf::Keyboard::F11:

     break;
  case sf::Keyboard::F12:

     break;
  case sf::Keyboard::F13:

     break;
  case sf::Keyboard::F14:

     break;
  case sf::Keyboard::F15:

     break;
  case sf::Keyboard::Pause:

     break;
  }
#+END_SRC
* Features
** Save prefix commands
